spring.application.name=EuroPolitik

spring.datasource.url=jdbc:postgresql://localhost:5432/europolitik
spring.datasource.username=europolitik
spring.datasource.password=europolitik

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false